# environment:
#   #- MONGO_INITDB_ROOT_USERNAME=user
#   #- MONGO_INITDB_ROOT_PASSWORD=password
#   - MONGO_INITDB_DATABASE="corretora"

version: "2.1"

services:
  # nginx:
  #   container_name: hackershall-dev-nginx
  #   image: nginx-dev-i
  #   build:
  #     context: .
  #     dockerfile: ./.docker/nginx.dev.dockerfile
  #   networks:
  #     - hackershall-network
  #   links:
  #     - node:node
  #   ports:
  #     - "80:80"

  app:
    container_name: corretora-app
    image: corretora-image
    build:
      context: .
      dockerfile: ./.docker/api.dev.dockerfile
    ports:
      - "4000:5000"
    networks:
      - corretora-network
    volumes:
      - ./api:/home/app
    env_file:
      - ./.docker/env/app.dev.env
    working_dir: /home/app
    depends_on:
      - mongo

  mongo:
    container_name: corretora-mongodb
    image: mongo:3.4.1
    build:
      context: .
      dockerfile: ./.docker/mongo.dev.dockerfile
    env_file:
      - ./.docker/env/mongo.dev.env
    networks:
      - corretora-network
    ports:
      - "27018:27017"

networks:
  corretora-network:
    driver: bridge